2020-11-02 16:12:34.983  INFO 36180 --- [restartedMain] com.de.Application                       : Starting Application on LAPTOP-5FPUV58C with PID 36180 (E:\Liao_java\gs_bishe\videoservice\target\classes started by lenovo in E:\Liao_java\gs_bishe)
2020-11-02 16:12:34.999  INFO 36180 --- [restartedMain] com.de.Application                       : No active profile set, falling back to default profiles: default
2020-11-02 16:12:35.127  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacv\1.5.1\javacv-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/javacpp-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/openblas-0.3.6-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/opencv-4.1.0-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/ffmpeg-4.1.3-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/flycapture-2.13.3.31-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/libdc1394-2.2.6-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/libfreenect-0.5.7-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/libfreenect2-0.2.0-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/librealsense-1.12.1-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/videoinput-0.200-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/artoolkitplus-2.3.1-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/flandmark-1.07-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/leptonica-1.78.0-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/tesseract-4.1.0-1.5.1.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/android-4.1.1.4.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-main-2.3.2.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2-natives-android-aarch64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2-natives-android-armv6.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2-natives-linux-amd64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2-natives-linux-armv6.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2-natives-linux-armv6hf.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2-natives-linux-i586.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2-natives-macosx-universal.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2-natives-solaris-amd64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2-natives-solaris-i586.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2-natives-windows-amd64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/gluegen-rt-2.3.2-natives-windows-i586.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-main-2.3.2.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2-natives-android-aarch64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2-natives-android-armv6.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2-natives-linux-amd64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2-natives-linux-armv6.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2-natives-linux-armv6hf.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2-natives-linux-i586.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2-natives-macosx-universal.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2-natives-solaris-amd64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2-natives-solaris-i586.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2-natives-windows-amd64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jogl-all-2.3.2-natives-windows-i586.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-main-2.3.2.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2-natives-android-aarch64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2-natives-android-armv6.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2-natives-linux-amd64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2-natives-linux-armv6.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2-natives-linux-armv6hf.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2-natives-linux-i586.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2-natives-macosx-universal.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2-natives-solaris-amd64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2-natives-solaris-i586.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2-natives-windows-amd64.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/jocl-2.3.2-natives-windows-i586.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/javacpp.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/openblas.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/opencv.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/ffmpeg.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/flycapture.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/libdc1394.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/libfreenect.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/libfreenect2.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/librealsense.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/videoinput.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/artoolkitplus.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/flandmark.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/leptonica.jar,file:/E:/MavenRepository/org/bytedeco/javacv/1.5.1/tesseract.jar
2020-11-02 16:12:35.159  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\openblas\0.3.6-1.5.1\openblas-0.3.6-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/openblas/0.3.6-1.5.1/javacpp.jar
2020-11-02 16:12:35.160  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\opencv\4.1.0-1.5.1\opencv-4.1.0-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/opencv/4.1.0-1.5.1/javacpp.jar
2020-11-02 16:12:35.160  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\ffmpeg\4.1.3-1.5.1\ffmpeg-4.1.3-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/ffmpeg/4.1.3-1.5.1/javacpp.jar
2020-11-02 16:12:35.160  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\flycapture\2.13.3.31-1.5.1\flycapture-2.13.3.31-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/flycapture/2.13.3.31-1.5.1/javacpp.jar
2020-11-02 16:12:35.161  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\libdc1394\2.2.6-1.5.1\libdc1394-2.2.6-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/libdc1394/2.2.6-1.5.1/javacpp.jar
2020-11-02 16:12:35.162  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\libfreenect\0.5.7-1.5.1\libfreenect-0.5.7-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/libfreenect/0.5.7-1.5.1/javacpp.jar
2020-11-02 16:12:35.162  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\libfreenect2\0.2.0-1.5.1\libfreenect2-0.2.0-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/libfreenect2/0.2.0-1.5.1/javacpp.jar
2020-11-02 16:12:35.162  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\librealsense\1.12.1-1.5.1\librealsense-1.12.1-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/librealsense/1.12.1-1.5.1/javacpp.jar
2020-11-02 16:12:35.162  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\videoinput\0.200-1.5.1\videoinput-0.200-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/videoinput/0.200-1.5.1/javacpp.jar
2020-11-02 16:12:35.162  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\artoolkitplus\2.3.1-1.5.1\artoolkitplus-2.3.1-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/artoolkitplus/2.3.1-1.5.1/javacpp.jar
2020-11-02 16:12:35.163  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\flandmark\1.07-1.5.1\flandmark-1.07-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/flandmark/1.07-1.5.1/javacpp.jar
2020-11-02 16:12:35.163  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\leptonica\1.78.0-1.5.1\leptonica-1.78.0-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/leptonica/1.78.0-1.5.1/javacpp.jar
2020-11-02 16:12:35.163  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\tesseract\4.1.0-1.5.1\tesseract-4.1.0-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/tesseract/4.1.0-1.5.1/javacpp.jar
2020-11-02 16:12:35.163  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\openblas-platform\0.3.6-1.5.1\openblas-platform-0.3.6-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/openblas-platform/0.3.6-1.5.1/openblas.jar,file:/E:/MavenRepository/org/bytedeco/openblas-platform/0.3.6-1.5.1/openblas-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/openblas-platform/0.3.6-1.5.1/openblas-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/openblas-platform/0.3.6-1.5.1/openblas-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/openblas-platform/0.3.6-1.5.1/openblas-linux-arm64.jar,file:/E:/MavenRepository/org/bytedeco/openblas-platform/0.3.6-1.5.1/openblas-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/openblas-platform/0.3.6-1.5.1/openblas-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/openblas-platform/0.3.6-1.5.1/openblas-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/openblas-platform/0.3.6-1.5.1/openblas-windows-x86_64.jar
2020-11-02 16:12:35.164  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\opencv-platform\4.1.0-1.5.1\opencv-platform-4.1.0-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/opencv-platform/4.1.0-1.5.1/opencv.jar,file:/E:/MavenRepository/org/bytedeco/opencv-platform/4.1.0-1.5.1/opencv-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/opencv-platform/4.1.0-1.5.1/opencv-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/opencv-platform/4.1.0-1.5.1/opencv-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/opencv-platform/4.1.0-1.5.1/opencv-linux-arm64.jar,file:/E:/MavenRepository/org/bytedeco/opencv-platform/4.1.0-1.5.1/opencv-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/opencv-platform/4.1.0-1.5.1/opencv-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/opencv-platform/4.1.0-1.5.1/opencv-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/opencv-platform/4.1.0-1.5.1/opencv-windows-x86_64.jar
2020-11-02 16:12:35.164  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\ffmpeg-platform\4.1.3-1.5.1\ffmpeg-platform-4.1.3-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/ffmpeg-platform/4.1.3-1.5.1/ffmpeg.jar,file:/E:/MavenRepository/org/bytedeco/ffmpeg-platform/4.1.3-1.5.1/ffmpeg-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/ffmpeg-platform/4.1.3-1.5.1/ffmpeg-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/ffmpeg-platform/4.1.3-1.5.1/ffmpeg-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/ffmpeg-platform/4.1.3-1.5.1/ffmpeg-linux-arm64.jar,file:/E:/MavenRepository/org/bytedeco/ffmpeg-platform/4.1.3-1.5.1/ffmpeg-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/ffmpeg-platform/4.1.3-1.5.1/ffmpeg-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/ffmpeg-platform/4.1.3-1.5.1/ffmpeg-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/ffmpeg-platform/4.1.3-1.5.1/ffmpeg-windows-x86_64.jar
2020-11-02 16:12:35.164  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\flycapture-platform\2.13.3.31-1.5.1\flycapture-platform-2.13.3.31-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/flycapture-platform/2.13.3.31-1.5.1/flycapture.jar,file:/E:/MavenRepository/org/bytedeco/flycapture-platform/2.13.3.31-1.5.1/flycapture-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/flycapture-platform/2.13.3.31-1.5.1/flycapture-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/flycapture-platform/2.13.3.31-1.5.1/flycapture-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/flycapture-platform/2.13.3.31-1.5.1/flycapture-linux-arm64.jar,file:/E:/MavenRepository/org/bytedeco/flycapture-platform/2.13.3.31-1.5.1/flycapture-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/flycapture-platform/2.13.3.31-1.5.1/flycapture-windows-x86_64.jar
2020-11-02 16:12:35.164  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\libdc1394-platform\2.2.6-1.5.1\libdc1394-platform-2.2.6-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/libdc1394-platform/2.2.6-1.5.1/libdc1394.jar,file:/E:/MavenRepository/org/bytedeco/libdc1394-platform/2.2.6-1.5.1/libdc1394-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/libdc1394-platform/2.2.6-1.5.1/libdc1394-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/libdc1394-platform/2.2.6-1.5.1/libdc1394-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/libdc1394-platform/2.2.6-1.5.1/libdc1394-linux-arm64.jar,file:/E:/MavenRepository/org/bytedeco/libdc1394-platform/2.2.6-1.5.1/libdc1394-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/libdc1394-platform/2.2.6-1.5.1/libdc1394-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/libdc1394-platform/2.2.6-1.5.1/libdc1394-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/libdc1394-platform/2.2.6-1.5.1/libdc1394-windows-x86_64.jar
2020-11-02 16:12:35.164  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\libfreenect-platform\0.5.7-1.5.1\libfreenect-platform-0.5.7-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/libfreenect-platform/0.5.7-1.5.1/libfreenect.jar,file:/E:/MavenRepository/org/bytedeco/libfreenect-platform/0.5.7-1.5.1/libfreenect-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/libfreenect-platform/0.5.7-1.5.1/libfreenect-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/libfreenect-platform/0.5.7-1.5.1/libfreenect-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/libfreenect-platform/0.5.7-1.5.1/libfreenect-linux-arm64.jar,file:/E:/MavenRepository/org/bytedeco/libfreenect-platform/0.5.7-1.5.1/libfreenect-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/libfreenect-platform/0.5.7-1.5.1/libfreenect-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/libfreenect-platform/0.5.7-1.5.1/libfreenect-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/libfreenect-platform/0.5.7-1.5.1/libfreenect-windows-x86_64.jar
2020-11-02 16:12:35.165  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\libfreenect2-platform\0.2.0-1.5.1\libfreenect2-platform-0.2.0-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/libfreenect2-platform/0.2.0-1.5.1/libfreenect2.jar,file:/E:/MavenRepository/org/bytedeco/libfreenect2-platform/0.2.0-1.5.1/libfreenect2-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/libfreenect2-platform/0.2.0-1.5.1/libfreenect2-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/libfreenect2-platform/0.2.0-1.5.1/libfreenect2-macosx-x86_64.jarlibfreenect2-windows-x86_64.jar
2020-11-02 16:12:35.165  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\librealsense-platform\1.12.1-1.5.1\librealsense-platform-1.12.1-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/librealsense-platform/1.12.1-1.5.1/librealsense.jar,file:/E:/MavenRepository/org/bytedeco/librealsense-platform/1.12.1-1.5.1/librealsense-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/librealsense-platform/1.12.1-1.5.1/librealsense-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/librealsense-platform/1.12.1-1.5.1/librealsense-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/librealsense-platform/1.12.1-1.5.1/librealsense-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/librealsense-platform/1.12.1-1.5.1/librealsense-windows-x86_64.jar
2020-11-02 16:12:35.165  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\videoinput-platform\0.200-1.5.1\videoinput-platform-0.200-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/videoinput-platform/0.200-1.5.1/videoinput.jar,file:/E:/MavenRepository/org/bytedeco/videoinput-platform/0.200-1.5.1/videoinput-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/videoinput-platform/0.200-1.5.1/videoinput-windows-x86_64.jar
2020-11-02 16:12:35.165  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\artoolkitplus-platform\2.3.1-1.5.1\artoolkitplus-platform-2.3.1-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/artoolkitplus-platform/2.3.1-1.5.1/artoolkitplus.jar,file:/E:/MavenRepository/org/bytedeco/artoolkitplus-platform/2.3.1-1.5.1/artoolkitplus-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/artoolkitplus-platform/2.3.1-1.5.1/artoolkitplus-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/artoolkitplus-platform/2.3.1-1.5.1/artoolkitplus-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/artoolkitplus-platform/2.3.1-1.5.1/artoolkitplus-linux-arm64.jar,file:/E:/MavenRepository/org/bytedeco/artoolkitplus-platform/2.3.1-1.5.1/artoolkitplus-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/artoolkitplus-platform/2.3.1-1.5.1/artoolkitplus-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/artoolkitplus-platform/2.3.1-1.5.1/artoolkitplus-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/artoolkitplus-platform/2.3.1-1.5.1/artoolkitplus-windows-x86_64.jar
2020-11-02 16:12:35.165  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\flandmark-platform\1.07-1.5.1\flandmark-platform-1.07-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/flandmark-platform/1.07-1.5.1/flandmark.jar,file:/E:/MavenRepository/org/bytedeco/flandmark-platform/1.07-1.5.1/flandmark-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/flandmark-platform/1.07-1.5.1/flandmark-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/flandmark-platform/1.07-1.5.1/flandmark-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/flandmark-platform/1.07-1.5.1/flandmark-linux-arm64.jar,file:/E:/MavenRepository/org/bytedeco/flandmark-platform/1.07-1.5.1/flandmark-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/flandmark-platform/1.07-1.5.1/flandmark-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/flandmark-platform/1.07-1.5.1/flandmark-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/flandmark-platform/1.07-1.5.1/flandmark-windows-x86_64.jar
2020-11-02 16:12:35.165  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\leptonica-platform\1.78.0-1.5.1\leptonica-platform-1.78.0-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/leptonica-platform/1.78.0-1.5.1/leptonica.jar,file:/E:/MavenRepository/org/bytedeco/leptonica-platform/1.78.0-1.5.1/leptonica-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/leptonica-platform/1.78.0-1.5.1/leptonica-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/leptonica-platform/1.78.0-1.5.1/leptonica-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/leptonica-platform/1.78.0-1.5.1/leptonica-linux-arm64.jar,file:/E:/MavenRepository/org/bytedeco/leptonica-platform/1.78.0-1.5.1/leptonica-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/leptonica-platform/1.78.0-1.5.1/leptonica-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/leptonica-platform/1.78.0-1.5.1/leptonica-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/leptonica-platform/1.78.0-1.5.1/leptonica-windows-x86_64.jar
2020-11-02 16:12:35.166  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\tesseract-platform\4.1.0-1.5.1\tesseract-platform-4.1.0-1.5.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/tesseract-platform/4.1.0-1.5.1/tesseract.jar,file:/E:/MavenRepository/org/bytedeco/tesseract-platform/4.1.0-1.5.1/tesseract-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/tesseract-platform/4.1.0-1.5.1/tesseract-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/tesseract-platform/4.1.0-1.5.1/tesseract-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/tesseract-platform/4.1.0-1.5.1/tesseract-linux-arm64.jar,file:/E:/MavenRepository/org/bytedeco/tesseract-platform/4.1.0-1.5.1/tesseract-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/tesseract-platform/4.1.0-1.5.1/tesseract-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/tesseract-platform/4.1.0-1.5.1/tesseract-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/tesseract-platform/4.1.0-1.5.1/tesseract-windows-x86_64.jar
2020-11-02 16:12:35.166  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\com\sun\xml\bind\jaxb-core\2.3.0\jaxb-core-2.3.0.jar referenced one or more files that do not exist: file:/E:/MavenRepository/com/sun/xml/bind/jaxb-core/2.3.0/jaxb-api.jar
2020-11-02 16:12:35.166  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacv-platform\1.4.1\javacv-platform-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacv-platform/1.4.1/javacv.jar,file:/E:/MavenRepository/org/bytedeco/javacv-platform/1.4.1/opencv-platform.jar,file:/E:/MavenRepository/org/bytedeco/javacv-platform/1.4.1/ffmpeg-platform.jar,file:/E:/MavenRepository/org/bytedeco/javacv-platform/1.4.1/flycapture-platform.jar,file:/E:/MavenRepository/org/bytedeco/javacv-platform/1.4.1/libdc1394-platform.jar,file:/E:/MavenRepository/org/bytedeco/javacv-platform/1.4.1/libfreenect-platform.jar,file:/E:/MavenRepository/org/bytedeco/javacv-platform/1.4.1/libfreenect2-platform.jar,file:/E:/MavenRepository/org/bytedeco/javacv-platform/1.4.1/librealsense-platform.jar,file:/E:/MavenRepository/org/bytedeco/javacv-platform/1.4.1/videoinput-platform.jar,file:/E:/MavenRepository/org/bytedeco/javacv-platform/1.4.1/artoolkitplus-platform.jar,file:/E:/MavenRepository/org/bytedeco/javacv-platform/1.4.1/flandmark-platform.jar
2020-11-02 16:12:35.166  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\ffmpeg-platform\3.4.2-1.4.1\ffmpeg-platform-3.4.2-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/ffmpeg-platform/3.4.2-1.4.1/ffmpeg.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/ffmpeg-platform/3.4.2-1.4.1/ffmpeg-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/ffmpeg-platform/3.4.2-1.4.1/ffmpeg-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/ffmpeg-platform/3.4.2-1.4.1/ffmpeg-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/ffmpeg-platform/3.4.2-1.4.1/ffmpeg-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/ffmpeg-platform/3.4.2-1.4.1/ffmpeg-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/ffmpeg-platform/3.4.2-1.4.1/ffmpeg-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/ffmpeg-platform/3.4.2-1.4.1/ffmpeg-windows-x86_64.jar
2020-11-02 16:12:35.167  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\ffmpeg\3.4.2-1.4.1\ffmpeg-3.4.2-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/ffmpeg/3.4.2-1.4.1/javacpp.jar
2020-11-02 16:12:35.171  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\flycapture-platform\2.11.3.121-1.4.1\flycapture-platform-2.11.3.121-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flycapture-platform/2.11.3.121-1.4.1/flycapture.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flycapture-platform/2.11.3.121-1.4.1/flycapture-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flycapture-platform/2.11.3.121-1.4.1/flycapture-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flycapture-platform/2.11.3.121-1.4.1/flycapture-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flycapture-platform/2.11.3.121-1.4.1/flycapture-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flycapture-platform/2.11.3.121-1.4.1/flycapture-windows-x86_64.jar
2020-11-02 16:12:35.171  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\flycapture\2.11.3.121-1.4.1\flycapture-2.11.3.121-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flycapture/2.11.3.121-1.4.1/javacpp.jar
2020-11-02 16:12:35.171  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\libdc1394-platform\2.2.5-1.4.1\libdc1394-platform-2.2.5-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libdc1394-platform/2.2.5-1.4.1/libdc1394.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libdc1394-platform/2.2.5-1.4.1/libdc1394-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libdc1394-platform/2.2.5-1.4.1/libdc1394-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libdc1394-platform/2.2.5-1.4.1/libdc1394-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libdc1394-platform/2.2.5-1.4.1/libdc1394-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libdc1394-platform/2.2.5-1.4.1/libdc1394-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libdc1394-platform/2.2.5-1.4.1/libdc1394-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libdc1394-platform/2.2.5-1.4.1/libdc1394-windows-x86_64.jar
2020-11-02 16:12:35.172  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\libdc1394\2.2.5-1.4.1\libdc1394-2.2.5-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libdc1394/2.2.5-1.4.1/javacpp.jar
2020-11-02 16:12:35.172  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\libfreenect-platform\0.5.3-1.4.1\libfreenect-platform-0.5.3-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect-platform/0.5.3-1.4.1/libfreenect.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect-platform/0.5.3-1.4.1/libfreenect-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect-platform/0.5.3-1.4.1/libfreenect-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect-platform/0.5.3-1.4.1/libfreenect-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect-platform/0.5.3-1.4.1/libfreenect-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect-platform/0.5.3-1.4.1/libfreenect-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect-platform/0.5.3-1.4.1/libfreenect-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect-platform/0.5.3-1.4.1/libfreenect-windows-x86_64.jar
2020-11-02 16:12:35.172  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\libfreenect\0.5.3-1.4.1\libfreenect-0.5.3-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect/0.5.3-1.4.1/javacpp.jar
2020-11-02 16:12:35.177  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\libfreenect2-platform\0.2.0-1.4.1\libfreenect2-platform-0.2.0-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect2-platform/0.2.0-1.4.1/libfreenect2.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect2-platform/0.2.0-1.4.1/libfreenect2-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect2-platform/0.2.0-1.4.1/libfreenect2-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect2-platform/0.2.0-1.4.1/libfreenect2-macosx-x86_64.jarlibfreenect2-windows-x86_64.jar
2020-11-02 16:12:35.177  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\libfreenect2\0.2.0-1.4.1\libfreenect2-0.2.0-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/libfreenect2/0.2.0-1.4.1/javacpp.jar
2020-11-02 16:12:35.177  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\librealsense-platform\1.12.1-1.4.1\librealsense-platform-1.12.1-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/librealsense-platform/1.12.1-1.4.1/librealsense.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/librealsense-platform/1.12.1-1.4.1/librealsense-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/librealsense-platform/1.12.1-1.4.1/librealsense-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/librealsense-platform/1.12.1-1.4.1/librealsense-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/librealsense-platform/1.12.1-1.4.1/librealsense-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/librealsense-platform/1.12.1-1.4.1/librealsense-windows-x86_64.jar
2020-11-02 16:12:35.179  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\librealsense\1.12.1-1.4.1\librealsense-1.12.1-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/librealsense/1.12.1-1.4.1/javacpp.jar
2020-11-02 16:12:35.179  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\videoinput-platform\0.200-1.4.1\videoinput-platform-0.200-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/videoinput-platform/0.200-1.4.1/videoinput.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/videoinput-platform/0.200-1.4.1/videoinput-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/videoinput-platform/0.200-1.4.1/videoinput-windows-x86_64.jar
2020-11-02 16:12:35.179  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\videoinput\0.200-1.4.1\videoinput-0.200-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/videoinput/0.200-1.4.1/javacpp.jar
2020-11-02 16:12:35.179  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\artoolkitplus-platform\2.3.1-1.4.1\artoolkitplus-platform-2.3.1-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/artoolkitplus-platform/2.3.1-1.4.1/artoolkitplus.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/artoolkitplus-platform/2.3.1-1.4.1/artoolkitplus-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/artoolkitplus-platform/2.3.1-1.4.1/artoolkitplus-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/artoolkitplus-platform/2.3.1-1.4.1/artoolkitplus-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/artoolkitplus-platform/2.3.1-1.4.1/artoolkitplus-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/artoolkitplus-platform/2.3.1-1.4.1/artoolkitplus-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/artoolkitplus-platform/2.3.1-1.4.1/artoolkitplus-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/artoolkitplus-platform/2.3.1-1.4.1/artoolkitplus-windows-x86_64.jar
2020-11-02 16:12:35.179  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.4.1\artoolkitplus-2.3.1-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.4.1/javacpp.jar
2020-11-02 16:12:35.179  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\flandmark-platform\1.07-1.4.1\flandmark-platform-1.07-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flandmark-platform/1.07-1.4.1/flandmark.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flandmark-platform/1.07-1.4.1/flandmark-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flandmark-platform/1.07-1.4.1/flandmark-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flandmark-platform/1.07-1.4.1/flandmark-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flandmark-platform/1.07-1.4.1/flandmark-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flandmark-platform/1.07-1.4.1/flandmark-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flandmark-platform/1.07-1.4.1/flandmark-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flandmark-platform/1.07-1.4.1/flandmark-windows-x86_64.jar
2020-11-02 16:12:35.180  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\flandmark\1.07-1.4.1\flandmark-1.07-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/flandmark/1.07-1.4.1/javacpp.jar
2020-11-02 16:12:35.180  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\opencv-platform\3.4.1-1.4.1\opencv-platform-3.4.1-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/opencv-platform/3.4.1-1.4.1/opencv.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/opencv-platform/3.4.1-1.4.1/opencv-linux-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/opencv-platform/3.4.1-1.4.1/opencv-linux-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/opencv-platform/3.4.1-1.4.1/opencv-linux-armhf.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/opencv-platform/3.4.1-1.4.1/opencv-linux-ppc64le.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/opencv-platform/3.4.1-1.4.1/opencv-macosx-x86_64.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/opencv-platform/3.4.1-1.4.1/opencv-windows-x86.jar,file:/E:/MavenRepository/org/bytedeco/javacpp-presets/opencv-platform/3.4.1-1.4.1/opencv-windows-x86_64.jar
2020-11-02 16:12:35.180  INFO 36180 --- [restartedMain] o.s.b.devtools.restart.ChangeableUrls    : The Class-Path manifest attribute in E:\MavenRepository\org\bytedeco\javacpp-presets\opencv\3.4.1-1.4.1\opencv-3.4.1-1.4.1.jar referenced one or more files that do not exist: file:/E:/MavenRepository/org/bytedeco/javacpp-presets/opencv/3.4.1-1.4.1/javacpp.jar
2020-11-02 16:12:35.180  INFO 36180 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2020-11-02 16:12:35.180  INFO 36180 --- [restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2020-11-02 16:12:38.070  INFO 36180 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-11-02 16:12:38.142  INFO 36180 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 30ms. Found 0 repository interfaces.
2020-11-02 16:12:39.480  INFO 36180 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-11-02 16:12:39.547  INFO 36180 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 66ms. Found 0 repository interfaces.
2020-11-02 16:12:39.555  INFO 36180 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-11-02 16:12:39.577  INFO 36180 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 21ms. Found 0 repository interfaces.
2020-11-02 16:12:40.364  INFO 36180 --- [restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-11-02 16:12:41.076  INFO 36180 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2020-11-02 16:12:41.102  INFO 36180 --- [restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-11-02 16:12:41.102  INFO 36180 --- [restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.27]
2020-11-02 16:12:41.350  INFO 36180 --- [restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-11-02 16:12:41.351  INFO 36180 --- [restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 6171 ms
2020-11-02 16:12:41.701  INFO 36180 --- [restartedMain] o.s.aop.framework.CglibAopProxy          : Unable to proxy interface-implementing method [public final void org.springframework.amqp.rabbit.core.RabbitTemplate.start()] because it is marked as final: Consider using interface-based JDK proxies instead!
2020-11-02 16:12:41.701  INFO 36180 --- [restartedMain] o.s.aop.framework.CglibAopProxy          : Unable to proxy interface-implementing method [public final void org.springframework.amqp.rabbit.core.RabbitTemplate.stop()] because it is marked as final: Consider using interface-based JDK proxies instead!
2020-11-02 16:12:42.057  INFO 36180 --- [restartedMain] c.a.d.s.b.a.DruidDataSourceAutoConfigure : Init DruidDataSource
2020-11-02 16:12:42.493  INFO 36180 --- [restartedMain] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2020-11-02 16:12:46.420  INFO 36180 --- [restartedMain] f.a.AutowiredAnnotationBeanPostProcessor : Autowired annotation is not supported on static fields: private static com.de.dao.CurCameraMapper com.de.service.impl.FrameRedisServiceImpl.curCameraMapper
2020-11-02 16:12:46.421  INFO 36180 --- [restartedMain] f.a.AutowiredAnnotationBeanPostProcessor : Autowired annotation is not supported on static fields: private static com.de.dao.PersonMapper com.de.service.impl.FrameRedisServiceImpl.personMapper
2020-11-02 16:12:46.421  INFO 36180 --- [restartedMain] f.a.AutowiredAnnotationBeanPostProcessor : Autowired annotation is not supported on static fields: private static com.de.dao.VideoMapper com.de.service.impl.FrameRedisServiceImpl.videoMapper
2020-11-02 16:12:46.421  INFO 36180 --- [restartedMain] f.a.AutowiredAnnotationBeanPostProcessor : Autowired annotation is not supported on static fields: private static java.lang.String com.de.service.impl.FrameRedisServiceImpl.mot_url
2020-11-02 16:12:46.421  INFO 36180 --- [restartedMain] f.a.AutowiredAnnotationBeanPostProcessor : Autowired annotation is not supported on static fields: private static java.lang.String com.de.service.impl.FrameRedisServiceImpl.save_dir
2020-11-02 16:12:46.568  INFO 36180 --- [restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-11-02 16:12:46.585  INFO 36180 --- [restartedMain] f.a.AutowiredAnnotationBeanPostProcessor : Autowired annotation is not supported on static fields: private static java.lang.String com.de.service.videoCalculate.Impl.VideoRedisServiceImpl.mot_url
2020-11-02 16:12:46.585  INFO 36180 --- [task-1] com.de.rtsp.MediaTransfer                : 连接rtsp：E:\video\1.mp4,开始创建grabber
2020-11-02 16:12:46.585  INFO 36180 --- [restartedMain] f.a.AutowiredAnnotationBeanPostProcessor : Autowired annotation is not supported on static fields: private static java.lang.String com.de.service.videoCalculate.Impl.VideoRedisServiceImpl.save_dir
2020-11-02 16:12:47.790  INFO 36180 --- [restartedMain] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2020-11-02 16:12:49.948  INFO 36180 --- [restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2020-11-02 16:12:49.955  INFO 36180 --- [restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2020-11-02 16:12:50.318  INFO 36180 --- [restartedMain] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [127.0.0.1:5672]
2020-11-02 16:12:50.636  INFO 36180 --- [task-1] com.de.rtsp.MediaTransfer                : 创建grabber成功
2020-11-02 16:12:50.775  INFO 36180 --- [restartedMain] o.s.a.r.c.CachingConnectionFactory       : Created new connection: connectionFactory#5877f6f4:0/SimpleConnection@1d2811d9 [delegate=amqp://guest@127.0.0.1:5672/, localPort= 49420]
2020-11-02 16:12:51.014  INFO 36180 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2020-11-02 16:12:51.023  INFO 36180 --- [restartedMain] com.de.Application                       : Started Application in 17.156 seconds (JVM running for 27.215)
2020-11-02 16:12:51.901  INFO 36180 --- [task-1] com.de.rtsp.MediaTransfer                : 启动grabber成功
2020-11-02 16:12:54.070  WARN 36180 --- [RMI TCP Connection(3)-10.135.162.238] s.b.a.e.ElasticsearchRestHealthIndicator : Elasticsearch health check failed

java.net.ConnectException: Timeout connecting to [localhost/127.0.0.1:9200]
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:959) ~[elasticsearch-rest-client-6.8.4.jar:6.8.4]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233) ~[elasticsearch-rest-client-6.8.4.jar:6.8.4]
	at org.springframework.boot.actuate.elasticsearch.ElasticsearchRestHealthIndicator.doHealthCheck(ElasticsearchRestHealthIndicator.java:60) ~[spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82) ~[spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:81) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:38) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:108) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:119) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:105) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:83) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:70) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:75) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:65) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:279) [spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:77) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:121) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:96) [spring-boot-actuator-2.2.1.RELEASE.jar:2.2.1.RELEASE]
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809) [na:na]
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466) [na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:75) [na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307) [na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399) [na:na]
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827) [na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:355) [na:na]
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200) [na:na]
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197) [na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) [na:na]
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196) [na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567) [na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:800) [na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:682) [na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) [na:na]
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
Caused by: java.net.ConnectException: Timeout connecting to [localhost/127.0.0.1:9200]
	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:169) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:628) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:894) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:184) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:214) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:158) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) ~[httpcore-nio-4.4.12.jar:4.4.12]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) ~[httpasyncclient-4.1.4.jar:4.1.4]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.4.jar:4.1.4]
	... 1 common frames omitted

2020-11-02 16:12:58.185  INFO 36180 --- [RMI TCP Connection(5)-10.135.162.238] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-11-02 16:12:58.185  INFO 36180 --- [RMI TCP Connection(5)-10.135.162.238] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-11-02 16:12:58.217  INFO 36180 --- [RMI TCP Connection(5)-10.135.162.238] o.s.web.servlet.DispatcherServlet        : Completed initialization in 32 ms
2020-11-02 16:12:59.161 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

2020-11-02 16:13:03.182 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

2020-11-02 16:13:05.336  INFO 36180 --- [http-nio-8080-exec-12] com.de.service.WebSocketServer           : 用户连接:0,当前在线人数为:1
2020-11-02 16:13:05.514 ERROR 36180 --- [http-nio-8080-exec-12] com.de.service.WebSocketServer           : 用户错误:0,原因:The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method
2020-11-02 16:13:05.520 ERROR 36180 --- [http-nio-8080-exec-12] com.de.service.WebSocketServer           : websocket error: 

java.lang.IllegalStateException: The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.checkState(WsRemoteEndpointImplBase.java:1229) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.textStart(WsRemoteEndpointImplBase.java:1191) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:190) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at com.de.service.WebSocketServer.sendMessageByStr(WebSocketServer.java:129) ~[classes/:na]
	at com.de.service.WebSocketServer.onOpen(WebSocketServer.java:71) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.apache.tomcat.websocket.pojo.PojoEndpointBase.doOnOpen(PojoEndpointBase.java:65) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.tomcat.websocket.pojo.PojoEndpointServer.onOpen(PojoEndpointServer.java:64) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:133) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:907) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]

2020-11-02 16:13:05.523  INFO 36180 --- [http-nio-8080-exec-12] com.de.service.WebSocketServer           : 用户退出:0,当前在线人数为:0
2020-11-02 16:13:05.525 ERROR 36180 --- [task-1] com.de.rtsp.MediaTransfer                : 因为异常，grabber关闭，rtsp连接断开，尝试重新连接
2020-11-02 16:13:05.526 ERROR 36180 --- [task-1] com.de.rtsp.MediaTransfer                : exception : 

java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:425) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:191) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendObject(WsRemoteEndpointImplBase.java:586) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendObject(WsRemoteEndpointBasic.java:74) ~[tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at com.de.service.WebSocketServer.sendMessageByObject(WebSocketServer.java:141) ~[classes/:na]
	at com.de.service.WebSocketServer.sendAllByObject(WebSocketServer.java:191) ~[classes/:na]
	at com.de.rtsp.MediaTransfer.startCameraPush(MediaTransfer.java:378) [classes/:na]
	at com.de.rtsp.MediaTransfer.live(MediaTransfer.java:303) [classes/:na]
	at com.de.rtsp.MediaTransfer$$FastClassBySpringCGLIB$$5a1bd220.invoke(<generated>) [classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) [spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) [spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) [spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]

2020-11-02 16:13:05.538  INFO 36180 --- [task-1] com.de.rtsp.MediaTransfer                : 重试连接rtsp：E:\video\1.mp4,开始创建grabber
2020-11-02 16:13:05.538  INFO 36180 --- [task-1] com.de.rtsp.MediaTransfer                : 创建grabber成功
2020-11-02 16:13:05.593  INFO 36180 --- [task-1] com.de.rtsp.MediaTransfer                : 启动grabber成功
2020-11-02 16:13:07.697 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

2020-11-02 16:13:12.203 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

2020-11-02 16:13:16.710 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

2020-11-02 16:13:21.242 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at jdk.internal.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

2020-11-02 16:13:26.057 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at jdk.internal.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

2020-11-02 16:13:30.587 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at jdk.internal.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

2020-11-02 16:13:35.331 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at jdk.internal.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

2020-11-02 16:13:39.854 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at jdk.internal.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

2020-11-02 16:13:44.895 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at jdk.internal.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

2020-11-02 16:13:49.451 ERROR 36180 --- [Druid-ConnectionPool-Create-704906419] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://localhost:3306/mot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at jdk.internal.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:787) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:712) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:680) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.18.jar:8.0.18]
	... 10 common frames omitted

